/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as CheckoutSlugRouteImport } from './routes/checkout.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin.banners'
import { Route as AuthenticatedAdminBeneficiosRouteImport } from './routes/_authenticated/admin.beneficios'
import { Route as AuthenticatedAdminCatalogoRouteImport } from './routes/_authenticated/admin.catalogo'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin.categorias'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin.clientes'
import { Route as AuthenticatedAdminCuponsRouteImport } from './routes/_authenticated/admin.cupons'
import { Route as AuthenticatedAdminDepoimentosRouteImport } from './routes/_authenticated/admin.depoimentos'
import { Route as AuthenticatedAdminDispositivosRouteImport } from './routes/_authenticated/admin.dispositivos'
import { Route as AuthenticatedAdminFaqRouteImport } from './routes/_authenticated/admin.faq'
import { Route as AuthenticatedAdminPagamentosRouteImport } from './routes/_authenticated/admin.pagamentos'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin.pedidos'
import { Route as AuthenticatedAdminPlanosRouteImport } from './routes/_authenticated/admin.planos'
import { Route as ApiPublicWebhooksPixgoRouteImport } from './routes/api/public/webhooks/pixgo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CheckoutSlugRoute = CheckoutSlugRouteImport.update({
  id: '/checkout/$slug',
  path: '/checkout/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBeneficiosRoute =
  AuthenticatedAdminBeneficiosRouteImport.update({
    id: '/beneficios',
    path: '/beneficios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCatalogoRoute =
  AuthenticatedAdminCatalogoRouteImport.update({
    id: '/catalogo',
    path: '/catalogo',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCuponsRoute =
  AuthenticatedAdminCuponsRouteImport.update({
    id: '/cupons',
    path: '/cupons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDepoimentosRoute =
  AuthenticatedAdminDepoimentosRouteImport.update({
    id: '/depoimentos',
    path: '/depoimentos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDispositivosRoute =
  AuthenticatedAdminDispositivosRouteImport.update({
    id: '/dispositivos',
    path: '/dispositivos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFaqRoute = AuthenticatedAdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPagamentosRoute =
  AuthenticatedAdminPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlanosRoute =
  AuthenticatedAdminPlanosRouteImport.update({
    id: '/planos',
    path: '/planos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicWebhooksPixgoRoute = ApiPublicWebhooksPixgoRouteImport.update({
  id: '/api/public/webhooks/pixgo',
  path: '/api/public/webhooks/pixgo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/beneficios': typeof AuthenticatedAdminBeneficiosRoute
  '/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/depoimentos': typeof AuthenticatedAdminDepoimentosRoute
  '/admin/dispositivos': typeof AuthenticatedAdminDispositivosRoute
  '/admin/faq': typeof AuthenticatedAdminFaqRoute
  '/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/planos': typeof AuthenticatedAdminPlanosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/pixgo': typeof ApiPublicWebhooksPixgoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/beneficios': typeof AuthenticatedAdminBeneficiosRoute
  '/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/depoimentos': typeof AuthenticatedAdminDepoimentosRoute
  '/admin/dispositivos': typeof AuthenticatedAdminDispositivosRoute
  '/admin/faq': typeof AuthenticatedAdminFaqRoute
  '/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/planos': typeof AuthenticatedAdminPlanosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/pixgo': typeof ApiPublicWebhooksPixgoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/beneficios': typeof AuthenticatedAdminBeneficiosRoute
  '/_authenticated/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/_authenticated/admin/depoimentos': typeof AuthenticatedAdminDepoimentosRoute
  '/_authenticated/admin/dispositivos': typeof AuthenticatedAdminDispositivosRoute
  '/_authenticated/admin/faq': typeof AuthenticatedAdminFaqRoute
  '/_authenticated/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/planos': typeof AuthenticatedAdminPlanosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/pixgo': typeof ApiPublicWebhooksPixgoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/termos'
    | '/admin'
    | '/checkout/$slug'
    | '/admin/banners'
    | '/admin/beneficios'
    | '/admin/catalogo'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/cupons'
    | '/admin/depoimentos'
    | '/admin/dispositivos'
    | '/admin/faq'
    | '/admin/pagamentos'
    | '/admin/pedidos'
    | '/admin/planos'
    | '/admin/'
    | '/api/public/webhooks/pixgo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/termos'
    | '/checkout/$slug'
    | '/admin/banners'
    | '/admin/beneficios'
    | '/admin/catalogo'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/cupons'
    | '/admin/depoimentos'
    | '/admin/dispositivos'
    | '/admin/faq'
    | '/admin/pagamentos'
    | '/admin/pedidos'
    | '/admin/planos'
    | '/admin'
    | '/api/public/webhooks/pixgo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacidade'
    | '/termos'
    | '/_authenticated/admin'
    | '/checkout/$slug'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/beneficios'
    | '/_authenticated/admin/catalogo'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/cupons'
    | '/_authenticated/admin/depoimentos'
    | '/_authenticated/admin/dispositivos'
    | '/_authenticated/admin/faq'
    | '/_authenticated/admin/pagamentos'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/planos'
    | '/_authenticated/admin/'
    | '/api/public/webhooks/pixgo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  CheckoutSlugRoute: typeof CheckoutSlugRoute
  ApiPublicWebhooksPixgoRoute: typeof ApiPublicWebhooksPixgoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/checkout/$slug': {
      id: '/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof CheckoutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/beneficios': {
      id: '/_authenticated/admin/beneficios'
      path: '/beneficios'
      fullPath: '/admin/beneficios'
      preLoaderRoute: typeof AuthenticatedAdminBeneficiosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/catalogo': {
      id: '/_authenticated/admin/catalogo'
      path: '/catalogo'
      fullPath: '/admin/catalogo'
      preLoaderRoute: typeof AuthenticatedAdminCatalogoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cupons': {
      id: '/_authenticated/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AuthenticatedAdminCuponsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/depoimentos': {
      id: '/_authenticated/admin/depoimentos'
      path: '/depoimentos'
      fullPath: '/admin/depoimentos'
      preLoaderRoute: typeof AuthenticatedAdminDepoimentosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dispositivos': {
      id: '/_authenticated/admin/dispositivos'
      path: '/dispositivos'
      fullPath: '/admin/dispositivos'
      preLoaderRoute: typeof AuthenticatedAdminDispositivosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/faq': {
      id: '/_authenticated/admin/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AuthenticatedAdminFaqRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pagamentos': {
      id: '/_authenticated/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AuthenticatedAdminPagamentosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/planos': {
      id: '/_authenticated/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AuthenticatedAdminPlanosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/webhooks/pixgo': {
      id: '/api/public/webhooks/pixgo'
      path: '/api/public/webhooks/pixgo'
      fullPath: '/api/public/webhooks/pixgo'
      preLoaderRoute: typeof ApiPublicWebhooksPixgoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminBeneficiosRoute: typeof AuthenticatedAdminBeneficiosRoute
  AuthenticatedAdminCatalogoRoute: typeof AuthenticatedAdminCatalogoRoute
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminCuponsRoute: typeof AuthenticatedAdminCuponsRoute
  AuthenticatedAdminDepoimentosRoute: typeof AuthenticatedAdminDepoimentosRoute
  AuthenticatedAdminDispositivosRoute: typeof AuthenticatedAdminDispositivosRoute
  AuthenticatedAdminFaqRoute: typeof AuthenticatedAdminFaqRoute
  AuthenticatedAdminPagamentosRoute: typeof AuthenticatedAdminPagamentosRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminPlanosRoute: typeof AuthenticatedAdminPlanosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
  AuthenticatedAdminBeneficiosRoute: AuthenticatedAdminBeneficiosRoute,
  AuthenticatedAdminCatalogoRoute: AuthenticatedAdminCatalogoRoute,
  AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminCuponsRoute: AuthenticatedAdminCuponsRoute,
  AuthenticatedAdminDepoimentosRoute: AuthenticatedAdminDepoimentosRoute,
  AuthenticatedAdminDispositivosRoute: AuthenticatedAdminDispositivosRoute,
  AuthenticatedAdminFaqRoute: AuthenticatedAdminFaqRoute,
  AuthenticatedAdminPagamentosRoute: AuthenticatedAdminPagamentosRoute,
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
  AuthenticatedAdminPlanosRoute: AuthenticatedAdminPlanosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  CheckoutSlugRoute: CheckoutSlugRoute,
  ApiPublicWebhooksPixgoRoute: ApiPublicWebhooksPixgoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
